
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microservice-client
server:
  port: 8201
eureka:
  client:
    service-url: http://localhost:7001/eureka/
---
spring:
  profiles: test
  application:
    name: microservice-client
server:
  port: 8202
eureka:
  client:
    service-url: http://localhost:7001/eureka/